### ISSUE TITLE
Failed to build 

### ISSUE THREAD

**Issue by mervynzhang** [scanoss/API#1]
Hi,

I got following error when trying to run "make".

1.  error: ‘for’ loop initial declarations are only allowed in C99 mode
Need add -std=gnu99 to CCFLAGS

2. src/utils/file_utils.h:49:1: error: unknown type name 'uint64_t'  

To fix this error, I have to add "#include <stdint.h>" to relevant files. 

 
3. ws.c:138: undefined reference to `SSL_CTX_set_ecdh_auto'  

To fix, I have to remove SSL_CTX_set_ecdh_auto(ctx, 1); 
 
Can you please verify if PR is needed to fix these errors. Thanks.

**Comment by scanossjs** [comment]
@mervynzhang what is the target OS? We have no errors on Debian 9 and 10.

**Comment by scanossjs** [comment]
Thanks. We have fixed this, see commit https://github.com/scanoss/API/commit/18ed60d51681e9f8998c61c421dfe7303e8fc123, but I'm afraid your point 3 doesn't seem right. SSL_CTX_set_ecdh_auto is part of the included library openssl/ssl.h as you can see from the official documentation: https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_set_ecdh_auto.html
