### ISSUE TITLE
API make error

### ISSUE THREAD

**Issue by cuiweining** [scanoss/API#8]
Hello, I encountered a make problem when using the API.
The questions are as follows:
After cloning the API, run make install wayuu, and then run make to report an error. How do you solve it?

cwn@cwn-Aspire-F5-572G:~/API$ make
rm -f  src/*.o src/**/*.o test/*.o test/**/*.o scanoss-api test-scanoss-api
gcc -g -Wall -std=gnu99 -o src/component.o -c src/component.c
gcc -g -Wall -std=gnu99 -o src/scan_direct.o -c src/scan_direct.c
src/scan_direct.c: In function ‘scan_direct_scan_request_handler’:
src/scan_direct.c:53:7: error: unknown type name ‘wayuu_error_t’
   53 |       wayuu_error_t *error = calloc(1, sizeof(wayuu_error_t));
      |       ^~~~~~~~~~~~~
src/scan_direct.c:53:47: error: ‘wayuu_error_t’ undeclared (first use in this function)
   53 |       wayuu_error_t *error = calloc(1, sizeof(wayuu_error_t));
      |                                               ^~~~~~~~~~~~~
src/scan_direct.c:53:47: note: each undeclared identifier is reported only once for each function it appears in
src/scan_direct.c:54:19: error: request for member ‘code’ in something not a structure or union
   54 |       strcpy(error->code, "INVALID");
      |                   ^~
src/scan_direct.c:55:19: error: request for member ‘message’ in something not a structure or union
   55 |       strcpy(error->message, "Invalid scan type");
      |                   ^~
src/scan_direct.c:56:35: warning: passing argument 2 of ‘bad_request_with_error’ from incompatible pointer type [-Wincompatible-pointer-types]
   56 |       bad_request_with_error(req, error);
      |                                   ^~~~~
      |                                   |
      |                                   int *
In file included from /usr/include/wayuu/wayuu.h:28,
                 from src/scan_direct.c:22:
/usr/include/wayuu/http_utils.h:172:56: note: expected ‘error_t *’ {aka ‘struct error_t *’} but argument is of type ‘int *’
  172 | void bad_request_with_error(api_request *req, error_t *error);
      |                                               ~~~~~~~~~^~~~~
make: *** [Makefile:33：src/scan_direct.o] error 1

**Comment by mscasso-scanoss** [comment]
Hi @cuiweining !! Nice to read you again. I was not able to reproduce the same bug that you are experimenting. But, let me guess: have you installed wayuu from the release package or cloning the repository? 
For the first case, We had forgotten to create a new one, so you were installing an old version of wayuu.I just created a new release (thank you).
 If you have installed wayuu cloning the repository, you will need to build and install the shared library. I have updated the Makefile to do this in a single step with "make all" and "make install". Please do a pull from master. 
Let me know if the problem persist. Thank you again.

**Comment by cuiweining** [comment]
Sorry, this problem is caused by the unsuccessful installation of wayuu. After the successful installation of wayuu components, you can use the compilation API normally!

However, this error occurs when running make test. Is this because I run a command less?
cwn@cwn-Aspire-F5-572G:~/API$ make run-valgrind
gcc -g -Wall -std=gnu99 -o src/component.o -c src/component.c
gcc -g -Wall -std=gnu99 -o src/scan_direct.o -c src/scan_direct.c
gcc -g -Wall -std=gnu99 -o src/main.o -c src/main.c
gcc -g -Wall -std=gnu99 -o src/bootstrap.o -c src/bootstrap.c
gcc -g -Wall -std=gnu99 -o src/attribution.o -c src/attribution.c
gcc -g -Wall -std=gnu99 -o src/utils/string_utils.o -c src/utils/string_utils.c
gcc -g -Wall -std=gnu99 -o src/utils/file_utils.o -c src/utils/file_utils.c
gcc -g -Wall -std=gnu99 -o src/utils/wfp_utils.o -c src/utils/wfp_utils.c
gcc -g -o scanoss-api src/component.o src/scan_direct.o src/main.o src/bootstrap.o src/attribution.o src/utils/string_utils.o src/utils/file_utils.o src/utils/wfp_utils.o  -lpthread -lssl -lwayuu -lm -lcrypto -I. 
rm -f src/*.o src/**/*.o 
valgrind --quiet --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 --keep-debuginfo=yes  ./scanoss-api -d 
make：valgrind：Command not found
make: *** [Makefile:48：run-valgrind] error 127

**Comment by cuiweining** [comment]
In addition, how to get the endpoint of the local API? I have no idea!

**Comment by mscasso-scanoss** [comment]
Hi @cuiweining! I've been working for you. Please check de API User Manual into the "doc" folder. Also I've updated the readme and the Makefile, improving the usability. 

The "make test" command run a series of test to check the correct working of the API during the development stage, I don't think that this is what your looking for.

Here you are an easier way of test it: https://docs.osskb.org/
Also, you can use a curl command like:

curl -vvvv -X GET "https://osskb.org/api/file_contents/864aa0b97465959b5287b2ef6de4011c" -H "accept: text/plain" -H  -P4443

(You can found more examples here: https://github.com/scanoss/API/blob/master/doc/SCANOSS%20API%20User%20Manual.pdf

**Comment by cuiweining** [comment]
OK, thank you very much for your answer.
